### ISSUE TITLE
Deployment 2020-2.0 checklist

### ISSUE THREAD

**Issue by mrakitin** [NSLS-II-BMM/profile_collection#6]
## Previsit 
- [ ] Make sure that the current latest environments are pushed to all the bl machines
- [ ] Skim the IPython startup files in `profile_collection`
  - Check if it's safe to start `bsui` remotely (does it touch any hardware?) - use `git grep .put` or `git grep caput`
- [ ] Check for outstanding PRs and issues on beamline repos
- [ ] Check if beamline specific packages pushed to the BL machines
- [ ] (Optional) Enable CI

## Housekeeping 
- [ ] Add BL staff to the BL GitHub organization as owners
- [ ] Work with BL staff to commit any un-committed changes to their profiles
- [ ] Tag the profile as-found as 2019C3.x
- [ ] Discuss with BL staff which conda envs they want to keep/delete and perform the cleanup
- [ ] Check/update the beamline's inventory with the BL staff (in https://github.com/NSLS-II/playbooks/blob/master/production)

## Test deployment 
- [ ] Run profile against new environment
  - `BS_ENV=collection-2020-2.0rc7 bsui`
- [ ] Update the profile as needed to run:
  - [ ] Replace `.value` -> `.get()` if it's in a `Device`, or with `yield from bps.read()` if in a plan
  - [ ] `history.sqlite` issue - see https://blueskyproject.io/bluesky/metadata.html#persistence-between-sessions
  - [ ] potential issue with images in databroker V2
- [ ] Run acceptance tests (if any) and run a representative set of scans for the beamline
- [ ] Tag the updated profile as `2020C2.0`
- [ ] Update BSUI via ansible to use the new environment (http://nsls-ii.github.io/deployment/upgrading-beamlines.html#change-bsui-s-default-environment)

**Comment by bruceravel** [comment]
Maksim, when do you want to do this?

**Comment by mrakitin** [comment]
Hi @bruceravel, we actually tested it during our call a month or so ago, and all major issues were resolved. It is more a formality on our side, and @tacaswell and @MikeHart85 are assigned to your beamline visit.

**Comment by mrakitin** [comment]
Closing as outdated.
